// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfqjcbnvllfnjhuvlmds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmcWpjYm52bGxmbmpodXZsbWRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2Mzk3NTYsImV4cCI6MjA3MTIxNTc1Nn0.IpxDvX72EpggZajTDJ2c5Iijg2WUsPiyIZIqL5w-4rQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});